### ISSUE TITLE
MaterialUI menu and in context editing

### ISSUE THREAD

**Issue by kasugaicrow** [tolgee/tolgee-js#1169]
Hi,
as you can see in this [sandbox](https://codesandbox.io/s/mystifying-blackburn-8ssq0) (React + MaterialUI library) I have a simple `Menu` with a `MenuItem` inside it. I need the `MenuItem` to be editable and so it is, but the moment I try to hover the input to go enter my translation, the input doesn't accept the focus.

To reproduce:
- open the [sandbox](https://codesandbox.io/s/mystifying-blackburn-8ssq0)
- go to `index.tsx` and compile `REACT_APP_TOLGEE_API_URL` and `REACT_APP_TOLGEE_API_KEY` with your account data
- click on `Open menu`
- `alt` + `click` to in context edit
- try to focus on input

Dependencies versions:
@tolgee/react: 2.8.0
@tolgee/ui: 2.8.0
react: 17.0.2
material-ui: 4.11.3

Let me know if you need something, thanks!

**Comment by JanCizmar** [comment]
Oh yes, this is known issue. This happens due to MaterialUI is periodically focusing the popover, which is wrapper of menu/modal or anything.

We can't do anything about it, because stealing focus from the popover element managed by MUI leads to infinite cycle of stealing focus from each other.

## Use external window
To translate strings like this, you can open translation dialog in popup window. By click this icon:

![Screenshot 2021-12-07 at 15 24 09](https://user-images.githubusercontent.com/18496315/145046750-6a50084a-c592-4020-bd12-16611a68f270.png)

**Comment by kasugaicrow** [comment]
I see, I'll go for the external window. Thank you
