### ISSUE TITLE
In Angular Service, any way to get the same functionality from onTranslationChange?

### ISSUE THREAD

**Issue by jmtt89** [tolgee/tolgee-js#3152]
In previous Tolgee release 4.X have a method onTranslationChange

```
onTranslationChange
EventEmmitter<TranslationData> emitting when translation is changed.

type TranslationData
{
    key: string; // the key which was changed
    translations: { // new translations for languages
        [key: string]: string;
    };
}

e.g.

{
    key: "i_am_a_key"
    translations: {
      "en": "English translation",
      "de": "German translation"
    };
}

```

But this method does not exist in the new version and I don't see any similar one in the API.

Is it possible to get the same functionality or some workaround?

**Comment by stepan662** [comment]
Hey, this is done differently in the new version. You can achieve a similar result with `on('cache', (e) => ...)` handler which is called every time something in the cache changes and the descriptor will tell you which part of a cache has been changed (e.g. `{ language: 'en', namespace: '', key: 'test_key' }`). The `key` property is there only if an individual translation was changed, which is the same case that you are describing above, I think.

If you want to get an actual value of the changed translation, you can read it from the cache like this:

```
tolgee.on('cache', ({ value }) => {
  if (value.key) {
    console.log(tolgee.getRecord(value)?.get(value.key));
  }
});
```

The event system was changed in v5, because before there were two kinds of events for `languageChange` and `keyChange` and we always had to subscribe for both of them in order to keep translations updated and it still was not reflecting all the usecases very well.

**Comment by jmtt89** [comment]
Thanks, I'll try then to use the events to get the changes.
