### ISSUE TITLE
Synchronoize updateHighlight to use the same root element defined in observerOptions

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-js#3161]
## Background

I'm trying to adapt Tolgee to a Gradio app. Briefly speaking, it is a Svelte application with all its elements constructed at runtime. 

## Problem faced

When the highlight key is pressed, the page highlights nothing.

## My research

The page has a special characteristic of having all its UI element hid in a shadow root.

![image](https://user-images.githubusercontent.com/2220320/220554141-cafd4866-c797-454b-95ca-1a4dd9da5dcc.png)

This led to several problems:

- The GeneralObserver is unable to discover anything, unless the shadow root is directly specified by `observerOptions.targetElement`
- The `updateHighlight` is using `document.elementFromPoint` and with the shadow root in place, all it returns is the shadow root. 

The second one is hardcoded but I tried to use `shadowRoot.elementFromPoint` in debugger and it does seem to work. Probably the `document` should be replaced with the specified root element?

![image](https://user-images.githubusercontent.com/2220320/220555229-3c176597-e355-4a57-8d51-6f1817f258d0.png)

**Comment by wfjsw** [comment]
Additionally, since the thing-to-observe have to be applied at runtime, it would be better if there is some way to reload the observer manually. Currently I have to call a `run()`, apply the translation, then `stop()` and `run()` again to have the observer reloaded.

**Comment by stepan662** [comment]
The shadow dom looks like an easy fix.

Any change of configuration or plugin addition causes tolgee to run `stop` <apply the changes> and then `run` again. So it shouldn't be necessary to call `stop` and `run` manually. The issue is that the observer observer is only started at the begining so if you changed the options later, it didn't get reflected. But I think I've found a solution for that.
