### ISSUE TITLE
Intentional translate through api 

### ISSUE THREAD

**Issue by ikbenignace** [tolgee/tolgee-js#3217]
I'm using tolgee with their purpose to instant translate through the api, since I'm also using it for dynamic data in my database, so new database items can be translated with tolgee. I add the keys to tolgee when an item is added in my database.

So for a long time I was just able to build production in angular and the translation just worked as intended, with an api key that can only read. But idk since when, but once I build in production I'm not able to get it working anymore, it only works in development. How can I fix this?

**Comment by stepan662** [comment]
Hey, I've tested it and it works for me. You have to make sure that `apiKey` and  `apiUrl` are present and also use `DevBackend` plugin, which is responsible for fetching data from Tolgee. It's part of the `DevTools` but it's omitted in production, so you need to add it manually.

```
const tolgee = Tolgee()
  .use(DevTools())
  .use(DevBackend())
 ...
```

Your issue might be caused by upgrading to SDK v5, because before this worked automatically if you included the `apiKey` and `apiUrl`.

**Comment by ikbenignace** [comment]
Thank you for your response, this helped me a lot :) Small thing but still.. haha
